# Generated by Django 4.2.3 on 2023-07-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contetn',
            new_name='content',
        ),
    ]
